### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by SNaveenMathew** [nyxtom/treetagger#3]
I ran the given example code and got the following error:
Traceback (most recent call last): File "<stdin>", line 1, in <module> File "build/bdist.linux-x86_64/egg/treetagger.py", line 141, in tag File "/usr/lib/python2.7/subprocess.py", line 710, in **init** errread, errwrite) File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child raise child_exception OSError: [Errno 8] Exec format error

**Comment by nyxtom** [comment]
Hmm, I'm not quite sure where that would stem from. Following the installation instructions here (http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger), I'm not doing anything particularly different to locate the tree-tagger-{language} script which would typically be located in the cmd directory.
